name: Build Il2CppDumper

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Il2CppDumper
      run: git clone https://github.com/roytu/Il2CppDumper.git

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Il2CppDumper/Il2CppDumper.sln

    - name: Build solution
      run: dotnet build Il2CppDumper/Il2CppDumper.sln --configuration Release --no-restore

    - name: Publish Il2CppDumper (net8.0)
      run: dotnet publish Il2CppDumper/Il2CppDumper/Il2CppDumper.csproj -c Release -f net8.0 -o out

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Il2CppDumper-build
        path: out
